### PR TITLE
[BISERVER-14442] - Database connections using connection pooling will not adhere to changes in the connection details

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins
@ssamora
@ppatricio
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by bcostahitachivantara** [comment]
This build will fail until https://github.com/pentaho/pentaho-kettle/pull/7535 be merged

**Comment by buildguy** [comment]
### :x: Build failed in 3m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 3m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PlatformKettleDataSourceProviderTest.testInvalidateNamedDataSource</b> (click to expand)</summary><p>

```
No method found with name 'getService' with parameter types: [ org.pentaho.platform.api.data.IPooledDatasourceService ] in class org.pentaho.platform.plugin.action.kettle.PlatformKettleDataSourceProvider.
```

</p></details>

  
Tests run: **22**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-83/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 2m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PlatformKettleDataSourceProviderTest.testInvalidateNamedDataSource</b> (click to expand)</summary><p>

```
No method found with name 'getService' with parameter types: [ org.pentaho.platform.api.data.IPooledDatasourceService ] in class org.pentaho.platform.plugin.action.kettle.PlatformKettleDataSourceProvider.
```

</p></details>

  
Tests run: **22**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-83/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 2m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PlatformKettleDataSourceProviderTest.testInvalidateNamedDataSource</b> (click to expand)</summary><p>

```
No method found with name 'getService' with parameter types: [ org.pentaho.platform.api.data.IPooledDatasourceService ] in class org.pentaho.platform.plugin.action.kettle.PlatformKettleDataSourceProvider.
```

</p></details>

  
Tests run: **22**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-83/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PlatformKettleDataSourceProviderTest.testInvalidateNamedDataSource</b> (click to expand)</summary><p>

```
No method found with name 'getService' with parameter types: [ org.pentaho.platform.api.data.IPooledDatasourceService ] in class org.pentaho.platform.plugin.action.kettle.PlatformKettleDataSourceProvider.
```

</p></details>

  
Tests run: **22**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-83/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **22**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-83/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
