### PR TITLE
[SP-5728] Backport of BISERVER-14442 - Database connections using con…

### PR DESCRIPTION
**Pull request by pentaho-lmartins**
…nection pooling will not adhere to changes in the connection details (8.3 Suite)

Cherry-pick of #83 into 8.3 branch.

Merge after https://github.com/pentaho/pentaho-kettle/pull/7710 and https://github.com/pentaho/pentaho-platform/pull/4763

@ssamora @ppatricio

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PdiActionTest.testTransformationInjector</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.kettle.PdiActionTest.testJobParameterPassing</b> (click to expand)</summary><p>

```
String index out of range: -1
```

</p></details>

  
Tests run: **22**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-85/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 2m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PdiActionTest.testTransformationInjector</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.kettle.PdiActionTest.testJobParameterPassing</b> (click to expand)</summary><p>

```
String index out of range: -1
```

</p></details>

  
Tests run: **22**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-85/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.kettle.PdiActionTest.testTransformationInjector</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.kettle.PdiActionTest.testJobParameterPassing</b> (click to expand)</summary><p>

```
String index out of range: -1
```

</p></details>

  
Tests run: **22**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi-platform-plugin/job/PR-85/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
